# Generated by Django 5.1.7 on 2025-03-16 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_initial_chains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('sender_previous_balance', models.DecimalField(decimal_places=8, max_digits=20)),
                ('sender_new_balance', models.DecimalField(decimal_places=8, max_digits=20)),
                ('recipient_previous_balance', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('recipient_new_balance', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coin')),
                ('counterparty_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wallet')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.wallet')),
            ],
        ),
    ]
