# Generated by Django 5.1.7 on 2025-03-19 18:42

from django.db import migrations


def create_initial_coins(apps, schema_editor):
    Chain = apps.get_model('api', 'Chain')
    Coin = apps.get_model('api', 'Coin')
    
    btc_chain = Chain.objects.get(symbol="BTC")
    eth_chain = Chain.objects.get(symbol="ETH")
    sol_chain = Chain.objects.get(symbol="SOL")

    coins = [
        {"chain": btc_chain, "name": "Bitcoin", "symbol": "BTC"},
        {"chain": btc_chain, "name": "Bitcoin Cash", "symbol": "BCH"},
        {"chain": btc_chain, "name": "Stacks", "symbol": "STX"},
        {"chain": btc_chain, "name": "Bitcoin SV", "symbol": "BSV"},

        {"chain": eth_chain, "name": "Ethereum", "symbol": "ETH"},
        {"chain": eth_chain, "name": "Chainlink", "symbol": "LINK"},
        {"chain": eth_chain, "name": "Shiba Inu", "symbol": "SHIB"},
        {"chain": eth_chain, "name": "USDC", "symbol": "USDC"},
        {"chain": eth_chain, "name": "Tether", "symbol": "USDT"},
        {"chain": eth_chain, "name": "Uniswap", "symbol": "UNI"},

        {"chain": sol_chain, "name": "Solana", "symbol": "SOL"},
        {"chain": sol_chain, "name": "Jupiter", "symbol": "JUP"},
        {"chain": sol_chain, "name": "The Graph", "symbol": "GRT"},
        {"chain": sol_chain, "name": "Decentraland", "symbol": "MANA"},
        {"chain": sol_chain, "name": "Arweave", "symbol": "AR"}
    ]
    for coin_data in coins:
        Coin.objects.get_or_create(
            symbol=coin_data["symbol"],
            defaults={
                "name": coin_data["name"],
                "chain": coin_data["chain"]
            }
        )

def remove_initial_coins(apps, schema_editor):
    Coin = apps.get_model('api', 'Coin')

    symbols = ["BTC", "BCH", "STX", "BSV", "ETH", "LINK", "SHIB", "USDC", "USDT", "UNI", "SOL", "JUP", "GRT", "MANA", "AR"]
    Coin.objects.filter(symbol__in=symbols).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction'),
    ]

    operations = [
            migrations.RunPython(create_initial_coins, remove_initial_coins)
    ]
